// email_digest.mjs — sends daily job digest email via Gmail SMTP
import { createTransport } from 'nodemailer';
import { CV } from './cv_profile.mjs';

const GMAIL_USER = process.env.GMAIL_USER || CV.email;
const GMAIL_PASS = process.env.GMAIL_APP_PASS; // Gmail App Password

export async function sendDigest(jobs, date) {
  if (!GMAIL_PASS) {
    console.warn('GMAIL_APP_PASS not set — writing digest to file instead');
    return writeDigestToFile(jobs, date);
  }

  const transport = createTransport({
    service: 'gmail',
    auth: { user: GMAIL_USER, pass: GMAIL_PASS },
  });

  const html = buildEmailHTML(jobs, date);
  const text = buildEmailText(jobs, date);

  await transport.sendMail({
    from: `"GREED Jobs Bot" <${GMAIL_USER}>`,
    to:   CV.email,
    subject: `🎯 ${jobs.length} Job Matches — ${date} | Top fit: ${jobs[0]?.fit?.score || 0}%`,
    html,
    text,
  });

  console.log(`Email sent to ${CV.email} — ${jobs.length} jobs`);
}

function buildEmailHTML(jobs, date) {
  const tierColour = t => t === 'STRONG' ? '#16a34a' : t === 'GOOD' ? '#2563eb' : '#d97706';

  const jobCards = jobs.slice(0, 15).map((j, i) => `
    <div style="border:1px solid #e5e7eb;border-radius:8px;padding:16px;margin-bottom:16px;">
      <div style="display:flex;justify-content:space-between;align-items:flex-start;">
        <div>
          <span style="background:${tierColour(j.fit.tier)};color:white;font-size:11px;padding:2px 8px;border-radius:4px;font-weight:600;">${j.fit.tier} ${j.fit.score}%</span>
          <h3 style="margin:6px 0 2px;font-size:16px;">${j.title}</h3>
          <p style="margin:0;color:#6b7280;font-size:14px;">${j.company} · ${j.location || 'UK'}</p>
          ${j.salary_text || j.fit.salary_detected ? `<p style="margin:4px 0;color:#059669;font-size:13px;font-weight:600;">${j.salary_text || '£' + j.fit.salary_detected?.toLocaleString()}</p>` : ''}
        </div>
        <a href="${j.url}" style="background:#0a66c2;color:white;padding:8px 14px;border-radius:6px;text-decoration:none;font-size:13px;white-space:nowrap;">
          ${j.easy_apply ? '⚡ Easy Apply' : 'View Job'}
        </a>
      </div>
      <div style="margin-top:10px;">
        <p style="margin:0;font-size:12px;color:#6b7280;">Matched: <strong>${j.fit.matched_skills.slice(0,6).join(', ')}</strong></p>
      </div>
      <details style="margin-top:10px;">
        <summary style="cursor:pointer;font-size:13px;color:#0a66c2;font-weight:600;">Cover letter →</summary>
        <pre style="margin-top:8px;font-family:Georgia,serif;font-size:13px;line-height:1.6;white-space:pre-wrap;background:#f9fafb;padding:12px;border-radius:6px;">${j.cover_letter}</pre>
      </details>
    </div>
  `).join('');

  return `
  <!DOCTYPE html>
  <html>
  <head><meta charset="utf-8"></head>
  <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:680px;margin:0 auto;padding:20px;color:#111;">
    <h1 style="font-size:22px;margin-bottom:4px;">Daily Job Digest — ${date}</h1>
    <p style="color:#6b7280;margin-top:0;">${jobs.length} matches found · Targeting £${CV.target.salary_min.toLocaleString()}–£${CV.target.salary_max.toLocaleString()} · UK</p>
    <hr style="border:none;border-top:1px solid #e5e7eb;margin:16px 0;">
    ${jobCards}
    <p style="margin-top:24px;font-size:12px;color:#9ca3af;">Generated by GREED Jobs Pipeline · ${new Date().toISOString()}</p>
  </body>
  </html>`;
}

function buildEmailText(jobs, date) {
  return [
    `DAILY JOB DIGEST — ${date}`,
    `${jobs.length} matches · Targeting £${CV.target.salary_min.toLocaleString()}+`,
    '='.repeat(60),
    ...jobs.slice(0, 15).map((j, i) => [
      `\n${i+1}. [${j.fit.tier} ${j.fit.score}%] ${j.title}`,
      `   ${j.company} · ${j.location || 'UK'}`,
      j.salary_text ? `   Salary: ${j.salary_text}` : '',
      `   Apply: ${j.url}`,
      `   Skills: ${j.fit.matched_skills.slice(0,5).join(', ')}`,
      `\nCOVER LETTER:\n${j.cover_letter}`,
      '-'.repeat(60),
    ].filter(Boolean).join('\n')),
  ].join('\n');
}

async function writeDigestToFile(jobs, date) {
  const { writeFileSync } = await import('fs');
  const outPath = `/home/ubuntu/trading-data/jobs/digest_${date}.txt`;
  writeFileSync(outPath, buildEmailText(jobs, date));
  console.log(`Digest written to ${outPath} (set GMAIL_APP_PASS to enable email)`);
}
