#!/bin/bash
# daily_report_cron.sh — EOD trade report for BOTH accounts (experiment 2131377 +
# scanner 2118552) combined into ONE email. Each is generated by daily_trade_report.mjs
# with its own cTrader env (separate node process), then stacked with a labeled banner.
set -u
MAILTO="toludavid07@gmail.com"
PROJECT_ROOT="/home/ubuntu/tradingview-mcp-jackson"
DATA_ROOT="/home/ubuntu/trading-data"
LOG_DIR="${DATA_ROOT}/pf_reflection"
DAILY_LOG="${LOG_DIR}/daily_report.cron.log"
HTML_FILE="${LOG_DIR}/daily_report.html"
TODAY="$(date -u +%Y-%m-%d)"; TS="$(date -Iseconds)"
mkdir -p "${LOG_DIR}"
cd "${PROJECT_ROOT}" || { echo "[$TS] cd failed" >> "$DAILY_LOG"; exit 99; }

gen() { ( set -a; . "/home/ubuntu/$1" 2>/dev/null; set +a; export BROKER_PROVIDER=ctrader
          node scripts/trading/daily_trade_report.mjs ); }

EXP_TXT="$(gen .ctrader_confirm.env 2>&1)"; EXP_EXIT=$?; cp -f "$HTML_FILE" /tmp/eod_exp.html 2>/dev/null || true
SCAN_TXT="$(gen .ctrader.env 2>&1)";        SCAN_EXIT=$?; cp -f "$HTML_FILE" /tmp/eod_scan.html 2>/dev/null || true
echo "[$TS] exp_exit=$EXP_EXIT scan_exit=$SCAN_EXIT" >> "$DAILY_LOG"

hdr() { printf '<div style="font:bold 15px -apple-system,Segoe UI,sans-serif;background:#111827;color:#fff;padding:10px 14px;margin-top:10px">%s</div>\n' "$1"; }
BOUNDARY="eodb_$(date +%s)_$$"
{
  printf 'To: %s\nFrom: %s\nSubject: [EOD] %s: trade report (experiment + scanner)\nMIME-Version: 1.0\nContent-Type: multipart/alternative; boundary="%s"\n\n' "$MAILTO" "$MAILTO" "$TODAY" "$BOUNDARY"
  printf -- '--%s\nContent-Type: text/plain; charset=utf-8\n\n' "$BOUNDARY"
  printf '===== EXPERIMENT  acct 2131377 =====\n%s\n\n===== SCANNER  acct 2118552 =====\n%s\n' "$EXP_TXT" "$SCAN_TXT"
  printf -- '\n--%s\nContent-Type: text/html; charset=utf-8\n\n' "$BOUNDARY"
  hdr 'EXPERIMENT &middot; acct 2131377'; [ -s /tmp/eod_exp.html ] && cat /tmp/eod_exp.html
  printf '<hr style="border:none;border-top:2px solid #888;margin:26px 0">'
  hdr 'SCANNER &middot; acct 2118552'; [ -s /tmp/eod_scan.html ] && cat /tmp/eod_scan.html
  printf '\n--%s--\n' "$BOUNDARY"
} | msmtp -t -a gmail || echo "[$TS] msmtp send failed (see msmtp.log)" >> "$DAILY_LOG"
rm -f /tmp/eod_exp.html /tmp/eod_scan.html
exit 0
