#!/bin/bash
# daily_report_cron.sh
# Wrapper for daily_trade_report.mjs — the single-day EOD trade report.
# Replaces pf_reflection_cron.sh in the nightly slot. Unlike the old 30-day
# reflection (which only emailed on flagged symbols), this ALWAYS emails the
# day's result so the operator gets one clear EOD summary every weekday —
# including "no trades today".
#
#   - Logs full output to disk
#   - Emails the HTML report (today's trades + results) on success (exit 0)
#   - On exit 2 (cTrader connection failure), emails a plain-text alert
#
# Requires: msmtp configured in ~/.msmtprc (gmail App Password).

set -u

MAILTO="toludavid07@gmail.com"
PROJECT_ROOT="/home/ubuntu/tradingview-mcp-jackson"
DATA_ROOT="/home/ubuntu/trading-data"
LOG_DIR="${DATA_ROOT}/pf_reflection"
DAILY_LOG="${LOG_DIR}/daily_report.cron.log"
HTML_FILE="${LOG_DIR}/daily_report.html"
HOSTNAME_TAG="$(hostname -s)"

mkdir -p "${LOG_DIR}"

cd "${PROJECT_ROOT}" || { echo "[$(date -Iseconds)] cd failed" >> "${DAILY_LOG}"; exit 99; }

# Source cTrader creds — cron does not inherit the scanner's env.
set -a
[ -r /home/ubuntu/.ctrader_env ] && . /home/ubuntu/.ctrader_env
set +a
export BROKER_PROVIDER=ctrader

OUTPUT="$(node scripts/trading/daily_trade_report.mjs 2>&1)"
EXIT=$?

TS="$(date -Iseconds)"
TODAY="$(date -u +%Y-%m-%d)"
echo "[${TS}] EXIT=${EXIT}" >> "${DAILY_LOG}"
echo "${OUTPUT}" >> "${DAILY_LOG}"

case "${EXIT}" in
  0)  SUBJECT="[EOD] ${TODAY}: daily trade report" ;;
  2)  SUBJECT="[EOD] ${HOSTNAME_TAG}: cTrader connection FAILED" ;;
  *)  SUBJECT="[EOD] ${HOSTNAME_TAG}: unexpected exit ${EXIT}" ;;
esac

BOUNDARY="eodb_$(date +%s)_$$"
INCLUDE_HTML=0
[ "${EXIT}" = "0" ] && [ -s "${HTML_FILE}" ] && INCLUDE_HTML=1

{
  printf 'To: %s\n' "${MAILTO}"
  printf 'From: %s\n' "${MAILTO}"
  printf 'Subject: %s\n' "${SUBJECT}"
  printf 'MIME-Version: 1.0\n'
  printf 'Content-Type: multipart/alternative; boundary="%s"\n\n' "${BOUNDARY}"

  printf -- '--%s\n' "${BOUNDARY}"
  printf 'Content-Type: text/plain; charset=utf-8\n\n'
  printf '%s\n\n' "${OUTPUT}"
  printf -- '--\nGenerated by daily_report_cron.sh @ %s\n' "${TS}"

  if [ "${INCLUDE_HTML}" = "1" ]; then
    printf -- '\n--%s\n' "${BOUNDARY}"
    printf 'Content-Type: text/html; charset=utf-8\n\n'
    cat "${HTML_FILE}"
    printf '\n'
  fi

  printf -- '--%s--\n' "${BOUNDARY}"
} | msmtp -t -a gmail || echo "[${TS}] msmtp send failed (see msmtp.log)" >> "${DAILY_LOG}"

exit "${EXIT}"
