#!/bin/bash
# pf_reflection_cron.sh
# Wrapper for per_symbol_pf_reflection.mjs.
#   - Always logs full output to disk
#   - On exit code 1 (≥1 active symbol below goal PF), emails the report
#   - On exit code 2 (cTrader connection failure), emails an alert
#   - On exit code 0 (all clear), silent — no email noise
#
# Requires: msmtp configured in ~/.msmtprc (currently failing auth — needs Gmail
# App Password refresh: https://myaccount.google.com/apppasswords).

set -u

MAILTO="toludavid07@gmail.com"
PROJECT_ROOT="/home/ubuntu/tradingview-mcp-jackson"
DATA_ROOT="/home/ubuntu/trading-data"
LOG_DIR="${DATA_ROOT}/pf_reflection"
DAILY_LOG="${LOG_DIR}/cron.log"
LAST_RUN="${LOG_DIR}/last_run.txt"
HOSTNAME_TAG="$(hostname -s)"

mkdir -p "${LOG_DIR}"

cd "${PROJECT_ROOT}" || { echo "[$(date -Iseconds)] cd failed" >> "${DAILY_LOG}"; exit 99; }

# Source cTrader creds + select provider. Cron does NOT inherit the scanner's
# env, so without this the reflection fails with "Missing CTRADER_* env vars"
# (exit 2) and emails a false "cTrader connection FAILED" alert.
set -a
[ -r /home/ubuntu/.ctrader_env ] && . /home/ubuntu/.ctrader_env
set +a
export BROKER_PROVIDER=ctrader

# Capture both stdout and stderr; save exit code separately
OUTPUT="$(node scripts/trading/per_symbol_pf_reflection.mjs 2>&1)"
EXIT=$?

TS="$(date -Iseconds)"
echo "[${TS}] EXIT=${EXIT}" >> "${DAILY_LOG}"
echo "${OUTPUT}" >> "${DAILY_LOG}"
echo "${TS} EXIT=${EXIT}" > "${LAST_RUN}"

# Decide whether to email
case "${EXIT}" in
  0)  # all clear, no email
      exit 0 ;;
  1)  SUBJECT="[PF reflection] ${HOSTNAME_TAG}: symbols below goal" ;;
  2)  SUBJECT="[PF reflection] ${HOSTNAME_TAG}: cTrader connection FAILED" ;;
  *)  SUBJECT="[PF reflection] ${HOSTNAME_TAG}: unexpected exit ${EXIT}" ;;
esac

# Send via msmtp as multipart/alternative: a rich HTML report (tables + bar
# charts, written by the .mjs to report.html) with the plain-text table as
# fallback. The HTML part is only attached on a successful report (exit 1) so we
# never email a stale chart on a cTrader-failure (exit 2). msmtp delivery
# failures land in /home/ubuntu/trading-data/msmtp.log.
HTML_FILE="${LOG_DIR}/report.html"
BOUNDARY="pfb_$(date +%s)_$$"
INCLUDE_HTML=0
[ "${EXIT}" = "1" ] && [ -s "${HTML_FILE}" ] && INCLUDE_HTML=1

{
  printf 'To: %s\n' "${MAILTO}"
  printf 'From: %s\n' "${MAILTO}"
  printf 'Subject: %s\n' "${SUBJECT}"
  printf 'MIME-Version: 1.0\n'
  printf 'Content-Type: multipart/alternative; boundary="%s"\n\n' "${BOUNDARY}"

  printf -- '--%s\n' "${BOUNDARY}"
  printf 'Content-Type: text/plain; charset=utf-8\n\n'
  printf '%s\n\n' "${OUTPUT}"
  printf -- '--\nGenerated by pf_reflection_cron.sh @ %s\n' "${TS}"

  if [ "${INCLUDE_HTML}" = "1" ]; then
    printf -- '\n--%s\n' "${BOUNDARY}"
    printf 'Content-Type: text/html; charset=utf-8\n\n'
    cat "${HTML_FILE}"
    printf '\n'
  fi

  printf -- '--%s--\n' "${BOUNDARY}"
} | msmtp -t -a gmail || echo "[${TS}] msmtp send failed (see msmtp.log)" >> "${DAILY_LOG}"

exit "${EXIT}"
