#!/bin/bash
# =============================================================================
#  TradingMCP — Oracle Cloud VM One-Time Setup Script
#  Run this ONCE on a fresh Ubuntu 22.04 ARM instance.
#
#  USAGE:
#    chmod +x oracle_setup.sh && sudo bash oracle_setup.sh
#
#  What it installs:
#    - Node.js 20 LTS
#    - Chromium (headless-capable, ARM-compatible)
#    - Xvfb (virtual display)
#    - x11vnc + fluxbox (for initial TradingView login via VNC)
#    - git, curl, unzip
#    - Clones/updates the tradingview-autopilot repo
#    - Sets timezone to Europe/London (matches UK trading times)
# =============================================================================

set -e

REPO_URL="https://github.com/YOUR_GITHUB_USERNAME/tradingview-autopilot.git"
INSTALL_DIR="/home/ubuntu/tradingview-autopilot"
NODE_VERSION="20"

echo ""
echo "=== TradingMCP Oracle Cloud Setup ==="
echo ""

# --- Timezone ------------------------------------------------------------------
echo "[1/7] Setting timezone to Europe/London..."
timedatectl set-timezone Europe/London
echo "      Done. Current time: $(date)"

# --- System packages -----------------------------------------------------------
echo "[2/7] Installing system packages..."
apt-get update -qq
apt-get install -y -qq \
    curl git unzip \
    xvfb x11vnc fluxbox \
    chromium-browser \
    fonts-liberation libappindicator3-1 libasound2 \
    libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 \
    libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 \
    libxcomposite1 libxdamage1 libxrandr2 xdg-utils \
    2>/dev/null
echo "      Done."

# --- Node.js ------------------------------------------------------------------
echo "[3/7] Installing Node.js $NODE_VERSION LTS..."
if ! command -v node &>/dev/null || [[ $(node -v | cut -d. -f1 | tr -d 'v') -lt $NODE_VERSION ]]; then
    curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - 2>/dev/null
    apt-get install -y -qq nodejs
fi
echo "      Node: $(node -v) | npm: $(npm -v)"

# --- Chromium binary detection -----------------------------------------------
echo "[4/7] Detecting Chromium binary..."
CHROMIUM_BIN=""
for bin in chromium-browser chromium google-chrome-stable google-chrome; do
    if command -v $bin &>/dev/null; then
        CHROMIUM_BIN=$(command -v $bin)
        break
    fi
done
if [ -z "$CHROMIUM_BIN" ]; then
    # Try snap
    if [ -f /snap/bin/chromium ]; then
        CHROMIUM_BIN=/snap/bin/chromium
    fi
fi
if [ -z "$CHROMIUM_BIN" ]; then
    echo "      WARNING: Chromium not found. Install manually: sudo snap install chromium"
else
    echo "      Found: $CHROMIUM_BIN"
    echo "      Version: $($CHROMIUM_BIN --version 2>/dev/null || echo 'unknown')"
fi

# --- Repo setup ---------------------------------------------------------------
echo "[5/7] Setting up project repository..."
if [ -d "$INSTALL_DIR/.git" ]; then
    echo "      Repo exists — pulling latest..."
    sudo -u ubuntu git -C "$INSTALL_DIR" pull --quiet
elif [ "$REPO_URL" != "https://github.com/YOUR_GITHUB_USERNAME/tradingview-autopilot.git" ]; then
    sudo -u ubuntu git clone "$REPO_URL" "$INSTALL_DIR"
else
    echo "      SKIP: Set REPO_URL at top of script to clone from GitHub."
    echo "      Or copy files manually: scp -r ./tradingview-autopilot ubuntu@<vm-ip>:~/"
fi

# --- npm install --------------------------------------------------------------
if [ -f "$INSTALL_DIR/package.json" ]; then
    echo "[6/7] Installing npm dependencies..."
    sudo -u ubuntu bash -c "cd '$INSTALL_DIR' && npm install --quiet"
else
    echo "[6/7] SKIP: No package.json found (copy repo first)."
fi

# --- Directories --------------------------------------------------------------
echo "[7/7] Creating runtime directories..."
sudo -u ubuntu mkdir -p \
    "$INSTALL_DIR/data/trade_log" \
    "$INSTALL_DIR/data/trade_log/scheduler_logs" \
    "$INSTALL_DIR/data/knowledge_base" \
    "$INSTALL_DIR/screenshots" \
    /home/ubuntu/.config/chromium-trading

chown -R ubuntu:ubuntu /home/ubuntu/.config/chromium-trading

# --- Write Chromium binary path to cloud config ------------------------------
CONFIG_FILE="$INSTALL_DIR/scripts/cloud/cloud_config.sh"
cat > "$CONFIG_FILE" <<EOF
# Auto-generated by oracle_setup.sh — do not edit manually
export CHROMIUM_BIN="$CHROMIUM_BIN"
export TV_PROJECT_DIR="$INSTALL_DIR"
export TV_CDP_PORT="9222"
export TV_DISPLAY=":99"
export TV_PROFILE_DIR="/home/ubuntu/.config/chromium-trading"
EOF
chown ubuntu:ubuntu "$CONFIG_FILE"
echo "      Config written to: $CONFIG_FILE"

echo ""
echo "=== Setup complete ==="
echo ""
echo "NEXT STEPS:"
echo "  1. Copy your repo to the VM (if not cloned above)"
echo "  2. Run: bash scripts/cloud/install_services.sh"
echo "  3. Run: bash scripts/cloud/setup_login_vnc.sh  (one-time TradingView login)"
echo "  4. Run: bash scripts/cloud/install_cron_linux.sh"
echo ""
echo "  See: scripts/cloud/ORACLE_CLOUD_SETUP.md for the full guide."
echo ""
